fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    eyplib: "https://github.com/NTTCom-MS/eyp-eyplib.git"
    systemd: "https://github.com/NTTCom-MS/eyp-systemd.git"
  symlinks:
    netplan: "#{source_dir}"
